version: "2"
services:
  server:
    build:
      context: .
      dockerfile: server.dev.Dockerfile
    networks:
      mdb:
      sig:
      srv:
        aliases:
          - apostille
    ports:
      - "8080"
      - "4443:4443"
    entrypoint: /usr/bin/env sh
    command: -c "./migrations/migrate.sh && apostille -config=fixtures/config.postgres.json"
    environment:
      QUAY_ROOT: quay.dev/*
      MIGRATIONS_PATH: migrations/postgresql
      DB_URL: postgres://server:12345@postgresql:5432/apostille?sslmode=disable
      ROOT_DB_URL: postgres://server_root:54321@postgresql:5432/apostille_root?sslmode=disable
    depends_on:
      - notary_signer
      - postgresql
  postgresql:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    networks:
      - mdb
      - sig
    volumes:
      - apostille_data:/var/lib/postgresql
    ports:
      - "5432:5432"
  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    command: python testclient.py
    networks:
      - mdb
      - srv
  notary_signer:
    build:
      context: .
      dockerfile: signer.Dockerfile
    networks:
      mdb:
      sig:
        aliases:
          - notarysigner
    entrypoint: /usr/bin/env sh
    environment:
      GOPATH: /go/src
      MIGRATIONS_PATH: /go/src/github.com/docker/notary/migrations/signer/postgresql
      DB_URL: postgres://signer@postgresql:5432/notarysigner?sslmode=disable
    command: -c "/migrate.sh && notary-signer -config=/signer-config.postgres.json"
    depends_on:
      - postgresql
volumes:
  apostille_data:
    external: false
networks:
  mdb:
    external: false
  srv:
    external: false
  sig:
    external: false
