version: "2"
services:
  server:
    build:
      context: .
      dockerfile: server.dev.Dockerfile
    networks:
      mdb:
      sig:
      srv:
        aliases:
          - apostille
    entrypoint: /usr/bin/env sh
    command: -c "./migrations/migrate.sh && apostille -config=fixtures/config.mysql.json"
    environment:
      DB_URL: mysql://server:12345@tcp(mysql:3306)/apostille
      ROOT_DB_URL: mysql://server_root:54321@tcp(mysql:3306)/apostille_root
    depends_on:
      - notary_signer
      - mysql
  mysql:
    networks:
      - mdb
      - sig
    build:
      context: .
      dockerfile: mysql.Dockerfile
    environment:
      - TERM=dumb
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    command: mysqld --innodb_file_per_table
    ports:
      - "3306:3306"
  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    command: python testclient.py
    networks:
      - mdb
      - srv
  notary_signer:
    build:
      context: .
      dockerfile: signer.Dockerfile
    networks:
      mdb:
      sig:
        aliases:
          - notarysigner
    entrypoint: /usr/bin/env sh
    environment:
      GOPATH: /go/src
      MIGRATIONS_PATH: /go/src/github.com/docker/notary/migrations/signer/mysql
      DB_URL: mysql://signer@tcp(mysql:3306)/notarysigner
    command: -c "/migrate.sh && notary-signer -config=/go/src/github.com/docker/notary/fixtures/signer-config.json"
    depends_on:
      - mysql
networks:
  mdb:
    external: false
  srv:
    external: false
  sig:
    external: false
