version: "2"
services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    networks:
      srv:
        aliases:
          - apostille
    entrypoint: /usr/bin/env sh
    command: -c "apostille -config=fixtures/config.mem.json"
    environment:
      - QUAY_ROOT=quay.io/*
  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    command: python testclient.py
    volumes:
      - ./test_output:/test_output
    networks:
      - srv
networks:
  srv:
    external: false
