kind: ConfigMap
apiVersion: v1
metadata:
  name: apostille-config
  namespace: apostille
  selfLink: /api/v1/namespaces/apostille/configmaps/apostille-config
data:
  config.prod.json: |
    {
      "server": {
        "http_addr": ":4443"
      },
      "trust_service": {
        "type": "remote",
        "hostname": "notarysigner",
        "port": "7899",
        "tls_ca_file": "/fixtures/notary/root-ca.crt",
        "key_algorithm": "ecdsa",
        "tls_client_cert": "/fixtures/notary/notary-server.crt",
        "tls_client_key": "/fixtures/notary/notary-server.key"
      },
      "logging": {
        "level": "debug"
      },
      "storage": {
        "backend": "mysql",
        "db_url": "postgres://apostille:UZZUjwhCyWxCL22EwGpcPNN6nUJfuHWxaq@apostille-v02.cb0vumcygprn.us-east-1.rds.amazonaws.com:5432/apostille"
      },
      "root_storage": {
        "backend": "mysql",
        "db_url": "postgres://apostille:UZZUjwhCyWxCL22EwGpcPNN6nUJfuHWxaq@apostille-v02.cb0vumcygprn.us-east-1.rds.amazonaws.com:5432/apostille",
        "root": "generate",
        "rootGUN": "quay.io/*"
      },
      "auth": {
        "type": "quaytoken",
        "options": {
          "realm": "https://quay.io:443",
          "service": "quay.io",
          "issuer": "quay",
          "keyserver": "https://quay.io/keys",
          "updateKeyInterval": "60s",
        }
      }
    }
  db.url: >-
    postgres://apostille:UZZUjwhCyWxCL22EwGpcPNN6nUJfuHWxaq@apostille-v02.cb0vumcygprn.us-east-1.rds.amazonaws.com:5432/apostille
  roots.db.url: >-
    postgres://apostille:UZZUjwhCyWxCL22EwGpcPNN6nUJfuHWxaq@apostille-v02.cb0vumcygprn.us-east-1.rds.amazonaws.com:5432/apostille
  migrations.path: migrations/postgresql

