kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{.Values.service}}
  namespace: {{.Values.apostille_namespace}}
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - {{.Values.service_subdomain}}.quay.io
      secretName: {{.Values.service}}-apostille-tls
  rules:
    - host: {{.Values.service_subdomain}}.quay.io
      http:
        paths:
          - path: /
            backend:
              serviceName: {{.Values.service}}
              servicePort: 4443