apiVersion: v1
kind: Secret
metadata:
  name: apostille-server-secrets
  namespace: apostille
type: Opaque
data:
  tls_ca: |
{{.Values.apostille_ca | b64enc | indent 4}}
  tls_client_cert: |
{{.Values.apostille_client_cert | b64enc | indent 4}}
  tls_client_key: |
{{.Values.apostille_client_key | b64enc | indent 4}}
---
apiVersion: v1
kind: Secret
metadata:
  name: apostille-signer-secrets
  namespace: apostille
type: Opaque
data:
  client_ca_file: |
{{.Values.apostille_ca | b64enc | indent 4}}
  tls_cert_file: |
{{.Values.signer_cert | b64enc | indent 4}}
  tls_key_file: |
{{.Values.signer_key | b64enc | indent 4}}
---
apiVersion: v1
kind: Secret
metadata:
  name: quay-apostille-pull-secret
  namespace: apostille
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJjWFZoZVN0aGNHOXpkR2xzYkdVNldWZGFTVWRaU1U1VldFZzJNRnBYVGtWYVVrMDJRVkl6UkRKS1RFUlFSVWhSTnpCWU1WQkVXVTAxVkZkUVdGQlZTMHhXTVRWWFNsTXhWVm8zVms0M1VRPT0iLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson
